package br.com.sabores.ejb.enums;

public enum TipoMensagemEmail 
{
	COMPRA_PARA_ADMINISTRADOR("NOTIFICA플O PARA SABORES DE COMPRA REALIZADA POR CLIENTE"), 
	COMPRA_PARA_CLIENTE("NOTIFICA플O DE COMPRA REALIZADA NO SITE SABORES NATURAIS"),
	ALTERACAO_COMPRA_PARA_ADMINISTRADOR("NOTIFICA플O PARA SABORES DE ALTERA플O DE COMPRA REALIZADA"),
	ALTERACAO_COMPRA_PARA_CLIENTE("NOTIFICA플O DE ALTERA플O DE COMPRA REALIZADA NO SITE SABORES NATURAIS"),
	CANCELAMENTO_COMPRA_PARA_CLIENTE("NOTIFICA플O DE CANCELAMENTO DE COMPRA REALIZADA NO SITE SABORES NATURAIS"),
	CANCELAMENTO_COMPRA_PARA_ADMINISTRADOR("NOTIFICA플O DE CANCELAMENTO DE COMPRA REALIZADA NO SITE SABORES NATURAIS"),
	ALTERACAO_SENHA_PARA_CLIENTE("NOTIFICA플O DE ALTERA플O DE SENHA PARA ACESSO AO SITE SABORES NATURAIS"), 
	RECUPERACAO_SENHA_PARA_CLIENTE("NOTIFICA플O DE RECUPERA플O DE SENHA PARA ACESSO AO SITE SABORES NATURAIS"),
	CADASTRO_PARA_CLIENTE("NOTIFICA플O DE CADASTRO EFETUADO NO SITE SABORES NATURAIS"), 
	CADASTRO_PARA_ADMINISTRADOR("NOTIFICA플O PARA SABORES DE CADASTRO EFETUADO"), 
	MALA_DIRETA_PARA_CLIENTES("FIQUE SABENDO DAS NOVIDADES DA NOSSA EMPRESA"),
	COMUNICADO_PARA_ADMINISTRADOR("COMUNICADO DE CLIENTE PARA ADMINISTRADOR"),
	ASSINATURA(""); //TODO
	
	TipoMensagemEmail(String dsc)
	{
		this.descricao = dsc;
	}
	
	private String descricao;
	
	public String getDescricao() 
	{
		return descricao;
	}
	
	public void setDescricao(String descricao) 
	{
		this.descricao = descricao;
	}
}
